version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade pip
  build:
    commands:
      - cd lambdas/ValidatorLambda
      - zip -r ../ValidatorLambda.zip .
      - |
        aws cloudformation package --template-file lambda_cf_template.yaml \
                                     --s3-bucket pipeline-cicd-serverless \
                                     --output-template-file packaged-template.yaml
artifacts:
  files:
    - packaged-template.yaml
    - lambdas/ValidatorLambda.zip
