version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade pip
  build:
    commands:
      # Package ValidatorLambda
      - cd lambdas/ValidatorLambda
      - zip -r ../../ValidatorLambda.zip .
      - cd ../..
      - aws cloudformation package \
          --template-file lambda_cf_template.yaml \
          --s3-bucket pipeline-cicd-serverless \
          --output-template-file ValidatorPackagedTemplate.yaml

      # Package DataLoaderLambda
      - cd lambdas/DataLoaderLambda
      - zip -r ../../DataLoaderLambda.zip .
      - cd ../..
      - aws cloudformation package \
          --template-file lambda_cf_template.yaml \
          --s3-bucket pipeline-cicd-serverless \
          --output-template-file DataLoaderPackagedTemplate.yaml

      # Package LoadUniversitiesLambda
      - cd lambdas/Universities
      - zip -r ../../LoadUniversitiesLambda.zip .
      - cd ../..
      - aws cloudformation package \
          --template-file lambda_cf_template.yaml \
          --s3-bucket pipeline-cicd-serverless \
          --output-template-file UniversitiesPackagedTemplate.yaml

artifacts:
  files:
    - ValidatorPackagedTemplate.yaml
    - ValidatorLambda.zip
    - DataLoaderPackagedTemplate.yaml
    - DataLoaderLambda.zip
    - UniversitiesPackagedTemplate.yaml
    - LoadUniversitiesLambda.zip
