version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade pip
  build:
    commands:
      # Package ValidatorLambda
      - cd lambdas/ValidatorLambda
      - zip -r ../../ValidatorLambda.zip .
      - cd ../..  # Navigate back to the project root directory
      - |
        aws cloudformation package \
          --template-file lambda_cf_template.yaml \
          --s3-bucket pipeline-cicd-serverless \
          --output-template-file ValidatorPackagedTemplate.yaml

      # Package DataLoaderLambda
      - cd lambdas/DataLoaderLambda
      - zip -r ../../DataLoaderLambda.zip .
      - cd ../..  # Navigate back to the project root directory
      - |
        aws cloudformation package \
          --template-file lambda_cf_template.yaml \
          --s3-bucket pipeline-cicd-serverless \
          --output-template-file DataLoaderPackagedTemplate.yaml

      # Package LoadUniversitiesLambda
      - cd lambdas/LoadUniversitiesLambda
      - zip -r ../../LoadUniversitiesLambda.zip .
      - cd ../..  # Navigate back to the project root directory
      - |
        aws cloudformation package \
          --template-file lambda_cf_template.yaml \
          --s3-bucket pipeline-cicd-serverless \
          --output-template-file UniversitiesPackagedTemplate.yaml
          
      # Upload Step Function flow.json
      - aws s3 cp step-function/flow.json s3://pipeline-cicd-serverless/step-function/flow.json


artifacts:
  files:
    - ValidatorPackagedTemplate.yaml
    - ValidatorLambda.zip
    - DataLoaderPackagedTemplate.yaml
    - DataLoaderLambda.zip
    - UniversitiesPackagedTemplate.yaml
    - LoadUniversitiesLambda.zip
    - lambda_cf_template.yaml  
