version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade pip
  build:
    commands:
      - cd lambdas/ValidatorLambda
      - zip -r ../ValidatorLambda.zip .  # Create a zip file of the ValidatorLambda code
      - cd ../..  # Navigate back to the project root directory
      - aws cloudformation package \
          --template-file lamda_cf_template.yaml \  # Use the correct template file name
          --s3-bucket pipeline-cicd-serverless \  # Specify the correct S3 bucket
          --output-template-file packaged-template.yaml  # Specify the output packaged template
artifacts:
  files:
    - packaged-template.yaml        # Include the CloudFormation packaged template
    - lambdas/ValidatorLambda.zip   # Include the Lambda deployment package
