AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for deploying multiple Lambda functions via CodePipeline.

Parameters:
  CodeBucket:
    Type: String
    Description: "The S3 bucket containing the Lambda deployment packages"
  ValidatorCodeKey:
    Type: String
    Description: "The S3 key for the ValidatorLambda deployment package"
  DataLoaderCodeKey:
    Type: String
    Description: "The S3 key for the DataLoaderLambda deployment package"
  UniversitiesCodeKey:
    Type: String
    Description: "The S3 key for the LoadUniversitiesLambda deployment package"

Resources:
  # Validator Lambda Function
  ValidatorLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.13
      Role: arn:aws:iam::592789829210:role/service-role/ValidatorLambda-role-vecq9y9u
      Code:
        S3Bucket: !Sub "${CodeBucket}"
        S3Key: !Sub "${ValidatorCodeKey}"
      Timeout: 30
      MemorySize: 128
      Description: "Validator Lambda function deployed via CodePipeline"

  # DataLoader Lambda Function
  DataLoaderLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.13
      Role: arn:aws:iam::592789829210:role/service-role/ValidatorLambda-role-vecq9y9u
      Code:
        S3Bucket: !Sub "${CodeBucket}"
        S3Key: !Sub "${DataLoaderCodeKey}"
      Timeout: 30
      MemorySize: 128
      Description: "DataLoader Lambda function deployed via CodePipeline"

  # Load Universities Lambda Function
  LoadUniversitiesLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.13
      Role: arn:aws:iam::592789829210:role/service-role/ValidatorLambda-role-vecq9y9u
      Code:
        S3Bucket: !Sub "${CodeBucket}"
        S3Key: !Sub "${UniversitiesCodeKey}"
      Timeout: 30
      MemorySize: 128
      Description: "Load Universities Lambda function deployed via CodePipeline"

Outputs:
  ValidatorLambdaFunctionArn:
    Description: "ARN of the Validator Lambda Function"
    Value: !GetAtt ValidatorLambdaFunction.Arn

  DataLoaderLambdaFunctionArn:
    Description: "ARN of the DataLoader Lambda Function"
    Value: !GetAtt DataLoaderLambdaFunction.Arn

  LoadUniversitiesLambdaFunctionArn:
    Description: "ARN of the Load Universities Lambda Function"
    Value: !GetAtt LoadUniversitiesLambdaFunction.Arn
