AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for deploying multiple Lambda functions and a Step Function via CodePipeline.

Parameters:
  CodeBucket:
    Type: String
    Description: "The S3 bucket containing the Lambda deployment packages"
  ValidatorCodeKey:
    Type: String
    Description: "The S3 key for the ValidatorLambda deployment package"
  DataLoaderCodeKey:
    Type: String
    Description: "The S3 key for the DataLoaderLambda deployment package"
  UniversitiesCodeKey:
    Type: String
    Description: "The S3 key for the LoadUniversitiesLambda deployment package"
  StepFunctionDefinitionKey:
    Type: String
    Default: "step-function/flow.json"
    Description: "The S3 key for the Step Function definition file"

Resources:
  # Validator Lambda Function
  ValidatorLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.13
      Role: arn:aws:iam::592789829210:role/service-role/ValidatorLambda-role-vecq9y9u
      Code:
        S3Bucket: !Sub "${CodeBucket}"
        S3Key: !Sub "${ValidatorCodeKey}"
      Timeout: 30
      MemorySize: 128
      Description: "Validator Lambda function deployed via CodePipeline"

  # DataLoader Lambda Function
  DataLoaderLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.13
      Role: arn:aws:iam::592789829210:role/service-role/ValidatorLambda-role-vecq9y9u
      Code:
        S3Bucket: !Sub "${CodeBucket}"
        S3Key: !Sub "${DataLoaderCodeKey}"
      Timeout: 30
      MemorySize: 128
      Description: "DataLoader Lambda function deployed via CodePipeline"

  # Load Universities Lambda Function
  LoadUniversitiesLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.13
      Role: arn:aws:iam::592789829210:role/service-role/ValidatorLambda-role-vecq9y9u
      Code:
        S3Bucket: !Sub "${CodeBucket}"
        S3Key: !Sub "${UniversitiesCodeKey}"
      Timeout: 30
      MemorySize: 128
      Description: "Load Universities Lambda function deployed via CodePipeline"

  # Step Function
  StateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: MyStepFunction
      DefinitionS3Location:
        Bucket: !Ref CodeBucket
        Key: !Ref StepFunctionDefinitionKey
      RoleArn: arn:aws:iam::592789829210:role/service-role/StepFunctions-MyStateMachine-wtou1f1my-role-47j7sgj16

Outputs:
  ValidatorLambdaFunctionArn:
    Description: "ARN of the Validator Lambda Function"
    Value: !GetAtt ValidatorLambdaFunction.Arn

  DataLoaderLambdaFunctionArn:
    Description: "ARN of the DataLoader Lambda Function"
    Value: !GetAtt DataLoaderLambdaFunction.Arn

  LoadUniversitiesLambdaFunctionArn:
    Description: "ARN of the Load Universities Lambda Function"
    Value: !GetAtt LoadUniversitiesLambdaFunction.Arn

  StateMachineArn:
    Description: "ARN of the Step Function"
    Value: !GetAtt StateMachine.Arn
